import type { NextPage } from "next";
import Head from "next/head";

import "bootstrap/dist/css/bootstrap.css";

// components
import Navigation from "../components/Landing-Page/Navigation/Navigation";

const Home: NextPage = () => {
   return (
      <>
         <Head>
            <title>Next App landing page</title>
            <meta name="description" content="Generated by create next app" />
         </Head>

         <>
            <Navigation />
         </>
      </>
   )
}

export default Home