import type { NextPage } from "next"
import Head from "next/head"
import Image from "next/image"
import styles from "../styles/modules/Home.module.css"

const Home: NextPage = () => {
   return (
      <>
         <Head>
            <title>Next App landing page</title>
            <meta name="description" content="Generated by create next app" />
         </Head>

         <div></div>
      </>
   )
}

export default Home
