/* eslint-disable curly */
import type { NextPage } from "next";
import Head from "next/head";
import { useRef } from "react";
import ErrorBoundary from "../src/components/ErrorBoundary";

interface user_info {
   firstName: string | undefined;
   lastName: string | undefined;
   middleName: string | undefined;
   age: number | undefined;
   address: string | undefined;
   email: string | undefined;
}

// components

const Home: NextPage = () => {

   const firstNameHolder = useRef<HTMLInputElement>(null);
   const lastNameHolder = useRef<HTMLInputElement>(null);
   const middleNameHolder = useRef<HTMLInputElement>(null);
   const ageHolder = useRef<HTMLInputElement>(null);
   const addressHolder = useRef<HTMLInputElement>(null);
   const emailHolder = useRef<HTMLInputElement>(null);

   function handleSubmit(): void {
      const user: user_info = {
         firstName: firstNameHolder.current?.value,
         lastName: lastNameHolder.current?.value,
         middleName: middleNameHolder.current?.value,
         age: parseFloat(ageHolder.current?.value as string),
         address: addressHolder.current?.value,
         email: emailHolder.current?.value,
      };

      if (!user.firstName) return;
      if (!user.lastName) return;
      if (!user.middleName) return;
      if (!user.age) return;
      if (!user.address) return;
      if (!user.email) return;
   }

   return (
      <>
         <Head>
            <title>Next App landing page</title>
            <meta name="description" content="Generated by create next app" />
         </Head>

         <ErrorBoundary>
            <div className="">
               <p>FirstName</p>
               <input type="text" ref={firstNameHolder} required />
               <p>LastName</p>
               <input type="text" ref={lastNameHolder} required />
               <p>MiddleName</p>
               <input type="text" ref={middleNameHolder} required />
               <p>Age</p>
               <input type="text" ref={ageHolder} required />
               <p>Address</p>
               <input type="text" ref={addressHolder} required />
               <p>Email</p>
               <input type="text" ref={emailHolder} required />
               <button type="submit" onClick={() => handleSubmit()}>
                  Submit
               </button>
            </div>
         </ErrorBoundary>
      </>
   );
};

export default Home;
